### PR TITLE
Add Algorithmia IPython Notebook example

### PR DESCRIPTION
**Pull request by besirkurtulmus**
Hey Donne,

Really liked the collection of notebooks. I thought it would be cool to also add Algorithmia to the index.

There's a lot of interesting algorithms on the platform. But I only showcased 4 of them as a simple introduction:
* Face Detection
* Content Summarizer
* Latent Dirichlet Allocation
* Optical Character Recognition

Tried to format the notebook according to your writing style as seen in the other notebooks.

Also, the logo won't show up properly on my fork because I've added the absolute path of your repo. Should render without a problem after you merge it.

Full disclosure: I work @Algorithmiaio

Cheers,
Besir

### CODE REVIEW

**Comment by besirkurtulmus** [comment]
I've noticed that I forgot to include the Algorithmia Python library for this notebook.

Can you please add `algorithmia==0.9.3` to the requirements.txt file.

**Comment by donnemartin** [comment]
Hi Ahmet,

Algorithmia looks pretty cool, thanks for the pull request!  I have a few comments:

* Could you place the notebook in the **misc** section?
* Many of the more specialized notebooks have setup instructions within the notebooks themselves, I think that might be a good place to add the `algorithmia` requirement.

-Donne

**Comment by besirkurtulmus** [comment]
Hi Donne,

I've updated the pull-request. Let me know if there's any other changes you require.

Thanks,
Besir

**Comment by donnemartin** [comment]
Nice work, thanks Besir!

**Pull request merged**
