### PR TITLE
Add tensor-flow-basic-tutorials

### PR DESCRIPTION
**Pull request by tuanavu**

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @tuanvu216, thanks for the pull request.

>These notebooks are derived from [learningtensorflow](http://learningtensorflow.com/)

Seems like a good resource, but do we have permission to use this content?

Terms and conditions:

http://learningtensorflow.com/t&c/

It seems like some of their content is paid:

http://learningtensorflow.com/paypalpages/buyanswers/

**Comment by tuanvu216** [comment]
Hi @donnemartin,

I believe we can use this content. The term and conditions said that the software does not contain any warranty. The paid content only for advanced tutorial and solutions of the homework, which you need to pay to get the package.

Thanks,
Tuan

**Comment by donnemartin** [comment]
Hi @tuanavu, I spoke with the author of learningtensorflow, he'd like for us to make the following changes:

* Only the first three tutorials can be on the repo (Variables/Arrays/Placeholders)
* We should not include exercises
* The material can't be changed in any significant way from the way it appears on the website
* Each notebook must display the below notice at the top of the page:

>This work comes from [LearningTensorFlow.com](http://learningtensorflow.com), developed by [dataPipeline](http://datapipeline.co.au), with whom the copyright remains.
For more tutorials and extended exercises, please see the website.

In the README.md , please include a hyperlink to the disclaimer notice from the website: http://learningtensorflow.com/t&c/

How do you feel about making these changes?

**Comment by tuanavu** [comment]
Hi @donnemartin,

Sounds good! I will make the changes in the notebooks and README. Then created another pull request.

Tuan

**Comment by tuanavu** [comment]
Hi @donnemartin,

I have made the changes you requested. Let's review and let me know what you think.

Thanks,
Tuan

**Comment by donnemartin** [comment]
Thanks @tuanavu, I'll try to free up in the next week or so for a review.

**Comment by donnemartin** [comment]
Hi @tuanavu, I've been giving this more thought, I think I'd prefer to link directly to your repo, similar to what we have with the following TF tutorials in the README:

>Additional TensorFlow tutorials:
>
>pkmital/tensorflow_tutorials
>nlintz/TensorFlow-Tutorials

How do you feel about adding your repo to the README and hosting the notebooks there?

>Additional TensorFlow tutorials:
>
>pkmital/tensorflow_tutorials
>nlintz/TensorFlow-Tutorials
>**tuanavu/foo**

Don't forget to update the [credits] section with your info :)

If this works for you, please submit a new PR.

**Comment by tuanavu** [comment]
Hosting notebooks in a new repo for tensorflow-basic-tutorials to resolve this PR.

**Pull request closed without merging**
